### ISSUE TITLE
This does not have an open-source license

### ISSUE THREAD

**Issue by Anonymous941** [OIRNOIR/Dankbot#1]
[You said in a message](https://discord.com/channels/808156208988422155/808165796106600499/885027819715956776) that your this is open-souce, however in order to be open-source it needs an open-source license.  As [a choose a license article says](https://choosealicense.com/no-permission/):

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

From a legal standpoint, the only exception is that you added:

> Redistribution is allowed.

This still means that nobody can modify or run this, nor does it mean it's open-source, only that it can be redistributed.

**Comment by OIRNOIR** [comment]
are you reading README.md or LICENSE.txt?
________________________________
From: Anonymous941 ***@***.***>
Sent: Saturday, September 11, 2021 9:21:38 AM
To: OIRNOIR/Dankbot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OIRNOIR/Dankbot] This does not have an open-source license (#1)


You said in a message<https://discord.com/channels/808156208988422155/808165796106600499/885027819715956776> that your this is open-souce, however in order to be open-source it needs an open-source license. As a choose a license article says<https://choosealicense.com/no-permission/>:

When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

From a legal standpoint, the only exception is that you added:

Redistribution is allowed.

This still means that nobody can modify or run this, nor does it mean it's open-source, only that it can be redistributed.

**Comment by OIRNOIR** [comment]
I'm not very good with the legal side of things. Basically, I want people to be able to run, use, modify, redistribute, or anything with this code, but I'm not liable if people f*ck it up. Can you maybe recommend a license to use?

**Comment by OIRNOIR** [comment]
Sorry for being unclear. This project uses the MIT license. I've added text saying that the license is in LICENSE.txt.
